services:
  - type: web
    name: intern-cert-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: intern-cert-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: BLOCKCHAIN_RPC_URL
        sync: false
      - key: SIGNER_PRIVATE_KEY
        sync: false

databases:
  - name: intern-cert-db
    plan: free
    region: singapore
